
language: python

env:
  global:
    - CGAT_TASK_STEPSIZE=100
  matrix:
    - CGAT_TASK_ID=1
    - TEST_STYLE=1
    - TEST_CMDLINE=0
    - TEST_IMPORT=0

python:
  - "2.7"

script: 
  - ./install-CGAT-tools.sh --travis

notifications:
  email:
    - sebastian.luna.valero@gmail.com
    - andreas.heger@gmail.com
    - david.sims@dpag.ox.ac.uk
    - stephen.sansom@kennedy.ox.ac.uk
    - i.sudbery@sheffield.ac.uk
    - jethro.johnson@dpag.ox.ac.uk
    - antonio.berlanga@dpag.ox.ac.uk
    - katherine.fawcett@dpag.ox.ac.uk
    - thomas.smith2@dpag.ox.ac.uk
    - michael.morgan@dpag.ox.ac.uk
    - xiaoming.hu@dpag.ox.ac.uk
    - nicholas.ilott@kennedy.ox.ac.uk
    - katherine.brown@dpag.ox.ac.uk
    - charlotte.george@dpag.ox.ac.uk
    - adam.cribbs@dpag.ox.ac.uk
